model:
  class_path: otx.algo.instance_segmentation.maskdino.MaskDINOR50
  init_args:
    label_info: 80

    optimizer:
      class_path: torch.optim.AdamW
      init_args:
        lr: 0.0001
        weight_decay: 0.0001

    scheduler:
      class_path: otx.core.schedulers.LinearWarmupSchedulerCallable
      init_args:
        num_warmup_steps: 100
        main_scheduler_callable:
          class_path: lightning.pytorch.cli.ReduceLROnPlateau
          init_args:
            mode: max
            factor: 0.1
            patience: 4
            monitor: val/map_50

engine:
  task: INSTANCE_SEGMENTATION
  device: auto

callback_monitor: val/map_50

data: ../_base_/data/instance_segmentation.yaml
overrides:
  max_epochs: 100
  gradient_clip_val: 35.0
  data:
    train_subset:
      batch_size: 2
      num_workers: 2
      transforms:
        - class_path: otx.core.data.transform_libs.torchvision.Pad
          init_args:
            size_divisor: 32

    val_subset:
      num_workers: 2
      transforms:
        - class_path: otx.core.data.transform_libs.torchvision.Pad
          init_args:
            size_divisor: 32

    test_subset:
      num_workers: 2
      transforms:
        - class_path: otx.core.data.transform_libs.torchvision.Pad
          init_args:
            size_divisor: 32
