model:
  class_path: otx.algo.instance_segmentation.rtdetr_inst.RTDetrInstResNet50
  init_args:
    label_info: 80

    optimizer:
      class_path: torch.optim.AdamW
      init_args:
        lr: 0.0001
        betas: [0.9, 0.999]
        weight_decay: 0.0001

    scheduler:
      class_path: otx.core.schedulers.LinearWarmupSchedulerCallable
      init_args:
        num_warmup_steps: 5
        main_scheduler_callable:
          class_path: lightning.pytorch.cli.ReduceLROnPlateau
          init_args:
            mode: max
            factor: 0.1
            patience: 6
            monitor: val/map_50

engine:
  task: INSTANCE_SEGMENTATION
  device: auto

callback_monitor: val/map_50

data: ../_base_/data/instance_segmentation.yaml
overrides:
  max_epochs: 100
  gradient_clip_val: 35.0
  data:
    train_subset:
      batch_size: 2
      num_workers: 2
      to_tv_image: True
      transforms:
        - class_path: otx.core.data.transform_libs.torchvision.Resize
          init_args:
            keep_ratio: false
            transform_bbox: true
            transform_mask: true
            is_numpy_to_tvtensor: true
            scale:
              - 640
              - 640
        - class_path: torchvision.transforms.v2.RandomHorizontalFlip
        - class_path: torchvision.transforms.v2.ToImage
        - class_path: torchvision.transforms.v2.ToDtype
          init_args:
            dtype: ${as_torch_dtype:torch.float32}
            scale: True
        - class_path: otx.core.data.transform_libs.torchvision.ConvertBox
          init_args:
            out_fmt: "cxcywh"
            normalize: True
    val_subset:
      batch_size: 1
      num_workers: 4
      transforms:
        - class_path: otx.core.data.transform_libs.torchvision.Resize
          init_args:
            keep_ratio: false
            is_numpy_to_tvtensor: true
            scale:
              - 640
              - 640
        - class_path: torchvision.transforms.v2.ToImage
        - class_path: torchvision.transforms.v2.ToDtype
          init_args:
            dtype: ${as_torch_dtype:torch.float32}
            scale: True
    test_subset:
      batch_size: 1
      num_workers: 4
      transforms:
        - class_path: otx.core.data.transform_libs.torchvision.Resize
          init_args:
            keep_ratio: false
            is_numpy_to_tvtensor: true
            scale:
              - 640
              - 640
        - class_path: torchvision.transforms.v2.ToImage
        - class_path: torchvision.transforms.v2.ToDtype
          init_args:
            dtype: ${as_torch_dtype:torch.float32}
            scale: True
